### ISSUE TITLE
checkChatInviteLink error

### ISSUE THREAD

**Issue by IMpIUVNvBk** [alexander-akhmetov/python-telegram#50] opened 2019-10-30 08:15 UTC
hey im using td 1.5.1 , python 3.7

data = {
            '@type': 'checkChatInviteLink',
            'invite_link ': link,
            }
    res = tg._send_data(data)
    res.wait()
    print(res.error_info)

prints :
{'@type': 'error', 'code': 3, 'message': 'Wrong invite link', '@extra': {'request_id': 'a3a0b4dcd9fb401bb4dcfdecc36425a1'}}

i test many links 
but i got same error.

**Comment by alexander-akhmetov** [comment] 2019-11-09 13:29
Hi, are you sure that you are passing full urls with a scheme? I can't reproduce the error and receive the correct response (but with td `1.5.0`, I haven't tried `1.5.1` yet.):

```
{'@type': 'chatInviteLinkInfo', 'chat_id': ..., 'type': {'@type': 'chatTypeBasicGroup', 'basic_group_id': ...}, 'title': '...', 'member_count': ..., 'member_user_ids': [], 'is_public': False, '@extra': {'request_id': '...'}}
```

I also suggest to use `call_method` instead of `_send_data`:

```
params = {'invite_link': link}
res = tg.call_method('checkChatInviteLink', params)
```

**Comment by alexander-akhmetov** [comment] 2020-01-30 19:12
I'm closing this for now, if it's still happens, please, re-open the issue.

**Closed by alexander-akhmetov** 2020-01-30 19:12 UTC
