### ISSUE TITLE
ARM architecture not supported on Mac OS X

### ISSUE THREAD

**Issue by MarioVilas** [alexander-akhmetov/python-telegram#466] opened 2024-05-06 17:52 UTC
```
marito@Marios-MacBook-Air cacabot % python3 example.py                        
Traceback (most recent call last):
  File "/Users/marito/Work/cacabot/example.py", line 4, in <module>
    tg = Telegram(
         ^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/telegram/client.py", line 147, in __init__
    self._tdjson = TDJson(library_path=library_path, verbosity=tdlib_verbosity)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/telegram/tdjson.py", line 33, in __init__
    self._build_client(library_path, verbosity)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/telegram/tdjson.py", line 40, in _build_client
    self._tdjson = CDLL(library_path)
                   ^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ctypes/__init__.py", line 379, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: dlopen(/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/telegram/lib/darwin/libtdjson.dylib, 0x0006): tried: '/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/telegram/lib/darwin/libtdjson.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/telegram/lib/darwin/libtdjson.dylib' (no such file), '/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/telegram/lib/darwin/libtdjson.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64'))
```

**Comment by gasaichandesu** [comment] 2024-06-04 14:00
Please see my PR #471

**Comment by alexander-akhmetov** [comment] 2024-06-22 22:30
Duplicate of #377

**Closed by alexander-akhmetov** 2024-06-22 22:30 UTC
